### ISSUE TITLE
Unable to collect from UNC path "--tsource '\\myserver\sharename' not available. Exiting"

### ISSUE THREAD

**Issue by eshock99** [EricZimmerman/KapeDocs#18]
Greetings,
I'm constantly asked to preserve user-created files in fileshares as part of subpeonas/etc for my university. It seems that various tools I've tried can never get around the 255-character file name limit gracefully. I am attempting to use Kape to collect/preserve these files.

I've tried a variety of syntax for this, but keep getting to the same error stating my tsource is not available. I've also tried it using a mapped drive with the same results.

I am:
Logged in the local machine with an admin account.
I have launched powershell with admin rights (same account as logged-on user).
I have access to the fileshare (i.e. I can browse there via UNC path (or mapped drive) without issue).

The same .tkape target file works if I use it locally, but I think it is erroring out before that is a factor anyway.

In the documentation, it mentions sharing out the C drive--is that absolutely necessary or will any valid share name work?

Here is an example input/output (but certainly not the only I've tried):

PS D:\temp\KAPE> .\kape.exe --tsource \\myserver\sharename --target unc_temp --tdest "D:\temp\files"

--tsource '\\myserver\sharename' not available. Exiting

TIA

**Comment by EricZimmerman** [comment]
first thing i notice is, you are not using two back slashes:

```
\\server\share
```

can you enable --debug?

i would highly recommend running FROM a unc share, ON the endpoint you want to collect, so you can get access to locked files and VSCs.

while KAPE can target unc paths, it cannot do locked files nor shadow copies.

@AndrewRathbun can you test/verify UNC paths on a test box?

**Comment by eshock99** [comment]
In my actual command, I do in fact have two backslashes--that was just a backspace error while obfuscating my server name.

I'm not sure I follow the FROM a unc share thing. The unc share in my case is hosted on a NetApp rather than a Windows file server. That's also why I mention my inability to share the C drive.

The end-users have a mapped drive on their workstation pointed to the share on the NetApp. My in-house legal counsel wants me to maintain a seperate "snapshot in time" copy of those files, typically without the end-user's knowledge, for subpoenas, open records requests, or research integrity investigations.

**Comment by EricZimmerman** [comment]
hmm, i dont have access to a netapp to test it, is it ntfs on the back end?

i didnt know if you were collecting from one machine to another vs a nas or similar.

**Comment by eshock99** [comment]
I have no idea what the filesystem is on the NetApp. Regardless, I'm having the same experience running my test cases targeting a Windows 2016 server that is NTFS.

**Comment by EricZimmerman** [comment]
just did a test with 1.1.0.1

worked fine

strange

![image](https://user-images.githubusercontent.com/4265254/142510217-9faec8ac-be0e-4c97-8889-f733f6c5d349.png)

**Comment by EricZimmerman** [comment]
lets see what andrew finds

**Comment by eshock99** [comment]
Ok great. I'll keep an eye out.

I've heard from Chad Tilbury that if you message Eric Zimmerman you should stay by the keyboard as he will respond quickly. Thanks for all you do.

**Comment by EricZimmerman** [comment]
i try!

**Comment by AndrewRathbun** [comment]
I'll be able to get to this tomorrow! I'll report back.

**Comment by AndrewRathbun** [comment]
> 
> 
> just did a test with 1.1.0.1
> 
> worked fine
> 
> strange
> 
> ![image](https://user-images.githubusercontent.com/4265254/142510217-9faec8ac-be0e-4c97-8889-f733f6c5d349.png)

Prefetch Target worked fine for me too.

`.\kape.exe --tsource \\127.0.0.1\c$ --tdest M:\Forensics\UNCtest\tout --tflush --target Prefetch--debug --gui`

![image](https://user-images.githubusercontent.com/36825567/142624222-4f09a4f3-eca6-4db2-9161-35bd0bf80d41.png)

A Target that covers locked files, such as FileSystem, did not work though.

`.\kape.exe --tsource \\127.0.0.1\c$ --tdest M:\Forensics\UNCtest\tout --tflush --target FileSystem --debug --gui`

![image](https://user-images.githubusercontent.com/36825567/142624283-5080a75b-528f-4fe8-933b-d80390242c84.png)

Some other observations for the good of the order:

Using KAPE hosted on a fixed drive but using the UNC path and pointing it towards the C drive's UNC path did not work.

```powershell
KAPE directory: \\127.0.0.1\c$\KAPE
Command line: --tsource \\127.0.0.1\c$ --tdest M:\Forensics\UNCtest\tout --tflush --target FileSystem --debug --gui
[removed all lines in between]
Copied 0 out of 7 files in 0.4032 seconds. File copy errors: 7. See console log for details! See '*_CopyLog.csv' in 'M:\Forensics\UNCtest\tout' for copy details
```

Using KAPE hosted on a fixed drive but using the UNC path grabbing Targets from a fixed drive path worked fine.

```powershell
KAPE directory: \\127.0.0.1\c$\KAPE
Command line: --tsource C:\ --tdest M:\Forensics\UNCtest\tout --tflush --target FileSystem --debug --gui
[removed all lines in between]
Copied 7 out of 7 files in 36.6722 seconds. See '*_CopyLog.csv' in 'M:\Forensics\UNCtest\tout' for copy details
```

Yes, I will update KAPE right after this post :)

If there's any more testing scenarios you want ran, let me know. I can try running from one of my NAS shares, too, if need be.
